cabal-version: 3.6
name:          bearlibterminal
version:       0.1.0.1
license:       MIT
copyright:     2024-2025 Avery
maintainer:    Avery <ppkfs@outlook.com>
author:        Avery
tested-with:   ghc ==9.8.2
homepage:      https://github.com/PPKFS/bearlibterminal-hs
bug-reports:   https://github.com/PPKFS/bearlibterminal-hs/issues
synopsis:
    Low-level Haskell bindings to the BearLibTerminal graphics library.

description:
    A Haskell wrapper for a graphics library for making roguelike-style games, with a terminal-like window facilitating flexible textual output and
    uncomplicated input processing. For more information and a design overview, please see the original documentation here: http://foo.wyrd.name/en:bearlibterminal.

category:      Game Development
build-type:    Simple

source-repository head
    type:     git
    location: https://github.com/PPKFS/bearlibterminal-hs.git

library
    exposed-modules:
        BearLibTerminal
        BearLibTerminal.Raw
        BearLibTerminal.Keycodes
        BearLibTerminal.Terminal.CString
        BearLibTerminal.Terminal.Color
        BearLibTerminal.Terminal.Print
        BearLibTerminal.Terminal.Set
        BearLibTerminal.Terminal.String
    cxx-options: -O3 -DNDEBUG -std=gnu++14 -fPIC -Wno-deprecated-declarations -DBearLibTerminal_EXPORTS -DTERMINAL_VERSION="Unknown" -DNDEBUG
    extra-libraries: freetype
    extra-lib-dirs: /opt/homebrew/lib
    extra-framework-dirs:
        /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks
    frameworks: AppKit
    extra-source-files:
      bearlibterminal/Terminal/Source/*.hpp
    cxx-sources:
        bearlibterminal/Terminal/Source/Atlas.cpp

        bearlibterminal/Terminal/Source/BOM.cpp

        bearlibterminal/Terminal/Source/Base64.cpp

        bearlibterminal/Terminal/Source/BearLibTerminal.cpp
        bearlibterminal/Terminal/Source/Bitmap.cpp

        bearlibterminal/Terminal/Source/BitmapTileset.cpp
        bearlibterminal/Terminal/Source/CocoaWindow.mm

        bearlibterminal/Terminal/Source/Config.cpp

        bearlibterminal/Terminal/Source/DynamicTileset.cpp

        bearlibterminal/Terminal/Source/Encoding.cpp


        bearlibterminal/Terminal/Source/Keystroke.cpp

        bearlibterminal/Terminal/Source/LoadBMP.cpp
        bearlibterminal/Terminal/Source/LoadBitmap.cpp

        bearlibterminal/Terminal/Source/LoadJPEG.cpp
        bearlibterminal/Terminal/Source/LoadPNG.cpp
        bearlibterminal/Terminal/Source/Log.cpp

        bearlibterminal/Terminal/Source/Luaopen.cpp
        bearlibterminal/Terminal/Source/OpenGL.cpp

        bearlibterminal/Terminal/Source/OptionGroup.cpp

        bearlibterminal/Terminal/Source/Options.cpp

        bearlibterminal/Terminal/Source/Palette.cpp

        bearlibterminal/Terminal/Source/Platform.cpp



        bearlibterminal/Terminal/Source/Resource.cpp

        bearlibterminal/Terminal/Source/SaveBMP.cpp

        bearlibterminal/Terminal/Source/Stage.cpp

        bearlibterminal/Terminal/Source/Terminal.cpp

        bearlibterminal/Terminal/Source/Texture.cpp

        bearlibterminal/Terminal/Source/Tileset.cpp

        bearlibterminal/Terminal/Source/TrueTypeTileset.cpp

        bearlibterminal/Terminal/Source/Utility.cpp

        bearlibterminal/Terminal/Source/WinApiWindow.cpp

        bearlibterminal/Terminal/Source/Window.cpp

        bearlibterminal/Terminal/Source/X11Window.cpp
        bearlibterminal/Terminal/Dependencies/PicoPNG/Source/PicoPNG.cpp
        bearlibterminal/Terminal/Dependencies/PicoPNG/Source/PicoPNG.cpp


    hs-source-dirs:     src
    default-language:   GHC2021
    default-extensions:
        DerivingStrategies OverloadedStrings MultiWayIf BlockArguments
        LambdaCase

    include-dirs:
      cbits
      bearlibterminal/Terminal/Source
      bearlibterminal/Terminal/./Include/C
      bearlibterminal/Terminal/./Dependencies/FreeType/Include
      bearlibterminal/Terminal/./Dependencies/PicoPNG/Include
      bearlibterminal/Terminal/./Dependencies/NanoJPEG/Include
    includes:
        cbits/BearLibTerminal.h
        cbits/BearLibTerminalExtras.h
    install-includes:
        cbits/BearLibTerminal.h
        cbits/BearLibTerminalExtras.h
        bearlibterminal/Terminal/Source/Base64.hpp
        bearlibterminal/Terminal/Source/Bitmap.hpp
        bearlibterminal/Terminal/Source/BitmapTileset.hpp
        bearlibterminal/Terminal/Source/BOM.hpp
        bearlibterminal/Terminal/Source/Builtin.Codepages.hpp
        bearlibterminal/Terminal/Source/Builtin.DefaultFont.hpp
        bearlibterminal/Terminal/Source/CocoaWindow.h
        bearlibterminal/Terminal/Source/Color.hpp
        bearlibterminal/Terminal/Source/Config.hpp
        bearlibterminal/Terminal/Source/DynamicTileset.hpp
        bearlibterminal/Terminal/Source/Encoding.hpp
        bearlibterminal/Terminal/Source/Geometry.hpp
        bearlibterminal/Terminal/Source/Keystroke.hpp
        bearlibterminal/Terminal/Source/LoadBitmap.hpp
        bearlibterminal/Terminal/Source/Log.hpp
        bearlibterminal/Terminal/Source/OpenGL.hpp
        bearlibterminal/Terminal/Source/OptionGroup.hpp
        bearlibterminal/Terminal/Source/Options.hpp
        bearlibterminal/Terminal/Source/Palette.hpp
        bearlibterminal/Terminal/Source/Platform.hpp
        bearlibterminal/Terminal/Source/Point.hpp
        bearlibterminal/Terminal/Source/Rectangle.hpp
        bearlibterminal/Terminal/Source/Resource.hpp
        bearlibterminal/Terminal/Source/Size.hpp
        bearlibterminal/Terminal/Source/Stage.hpp
        bearlibterminal/Terminal/Source/Terminal.hpp
        bearlibterminal/Terminal/Source/Texture.hpp
        bearlibterminal/Terminal/Source/Tileset.hpp
        bearlibterminal/Terminal/Source/TrueTypeTileset.hpp
        bearlibterminal/Terminal/Source/Utility.hpp
        bearlibterminal/Terminal/Source/WinApiWindow.hpp
        bearlibterminal/Terminal/Source/Window.hpp
        bearlibterminal/Terminal/Source/X11Window.hpp
        bearlibterminal/Terminal/Source/Atlas.hpp
        bearlibterminal/Terminal/Dependencies/NanoJPEG/Include/NanoJPEG.h
        bearlibterminal/Terminal/Dependencies/PicoPNG/Include/PicoPNG.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftxf86.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftsnames.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftwinfnt.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftsizes.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/fttypes.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftmm.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/config/ftstdlib.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/config/ftheader.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/config/ftconfig.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/config/ftoption.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/config/ftmodule.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftmodapi.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftbzip2.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ttunpat.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/fttrigon.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftbbox.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftgzip.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/sfnt.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/internal.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftdebug.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/psaux.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/t1types.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/pshints.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftdriver.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/autohint.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftstream.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/tttypes.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftvalid.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftobjs.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftpic.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/fttrace.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftmemory.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftgloadr.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftserv.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svmm.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svwinfnt.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svttcmap.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svotval.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svgldict.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svpscmap.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svkern.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svpsinfo.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svpfr.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svgxval.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svxf86nm.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svbdf.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svsfnt.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svtteng.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svcid.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svttglyf.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/services/svpostnm.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftrfork.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/internal/ftcalc.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftoutln.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftadvanc.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftsynth.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/fterrors.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftgasp.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftstroke.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftcache.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftotval.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/freetype.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftincrem.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/fterrdef.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ttnameid.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftpfr.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftgxval.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftchapters.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/tttags.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftlzw.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftsystem.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/t1tables.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftimage.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/tttables.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftcid.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftglyph.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftmoderr.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftbitmap.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftlist.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftmac.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftlcdfil.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftbdf.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/freetype/ftrender.h
        bearlibterminal/Terminal/Dependencies/FreeType/Include/ft2build.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/ttcmap.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/ttpost.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/sfntpic.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/ttload.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/ttbdf.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/ttcmapc.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/ttkern.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/sfobjs.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/ttmtx.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/ttsbit.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/sfdriver.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/sfnt/sferrors.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/smooth/ftsmooth.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/smooth/ftspic.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/smooth/ftsmerrs.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/smooth/ftgrays.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afindic.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afdummy.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afmodule.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afhints.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afloader.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/aflatin2.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/aferrors.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afpic.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afglobal.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afwarp.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/aftypes.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afcjk.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/aflatin.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/autofit/afangles.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/truetype/tterrors.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/truetype/ttdriver.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/truetype/ttpic.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/truetype/ttgload.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/truetype/ttgxvar.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/truetype/ttpload.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/truetype/ttinterp.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/truetype/ttobjs.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/raster/ftmisc.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/raster/rasterrs.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/raster/ftrend1.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/raster/ftraster.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/raster/rastpic.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/base/basepic.h
        bearlibterminal/Terminal/Dependencies/FreeType/Source/base/ftbase.h
    ghc-options:
        -Wall -Wcompat -Widentities -Wredundant-constraints
        -Wno-unused-packages -Wno-deprecations -fhide-source-paths
        -Wno-unused-top-binds -Wmissing-deriving-strategies -haddock -g

    build-depends:
        base >=4.17.2 && <5,
        text >=2.1.1 && <3,
        bytestring >=0.12.1 && <2,
        mtl >=2.3.1 && <3

executable omni
    main-is:            Main.hs
    hs-source-dirs:     omni
    other-modules:
        Omni.BasicOutput
        Omni.DefaultFont
        Omni.Tilesets
        Omni.ManualCellsize

    default-language:   GHC2021
    default-extensions:
        DerivingStrategies OverloadedStrings MultiWayIf BlockArguments
        LambdaCase

    ghc-options:
        -Wall -Wcompat -Widentities -Wredundant-constraints
        -Wno-unused-packages -Wno-deprecations -fhide-source-paths
        -Wno-unused-top-binds -Wmissing-deriving-strategies -haddock -g

    build-depends:
        base >=4.17.2 && <5,
        text >=2.1.1 && <3,
        bytestring >=0.12.1 && <2,
        mtl >=2.3.1 && <3,
        bearlibterminal >=0.1.0.0 && <=0.2.0.0,
        containers >=0.6.8 && <1,
        formatting >=7.2.0 && <8,
        time >=1.12.2 && <2,
        random >=1.3.0 && <2,
        vector >=0.13.2 && <1,
        word8 >=0.1.3 && <1
